name: Build Wheels

on:
  pull_request:

env:
  BINDING_DIR: runtime/binding/python

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install torch
        run: pip install torch==1.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.5.0

      - name: Build wheels
        run: |
          cd ${{ env.BINDING_DIR }}
          python -m cibuildwheel --output-dir wheelhouse
